@ShoppingCart.App_HostAddress = http://localhost:5164

GET {{ShoppingCart.App_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{ShoppingCart.App_HostAddress}}/api/users
Accept: application/json
